### PR TITLE
Vizier fixes

### PR DESCRIPTION
**Pull request by mattwhiting**
Think this is ready for incorporation.
The fixes here simply add a check for the size of the table returned by the `query_region` function. If this is empty, then its `keys()` call will be empty and it will fail to get the relevant catalogue data. 
If we test for the desired catalogue being in the table, then we can either write the results out or write out a dummy file (in this case one with "No sources found" in it).
Implemented this fix for the FIRST & NVSS functions (as well as HIPASS, even though it's not used).

### CODE REVIEW

**Comment by biqingfor** [comment]
@mattwhiting : i don't remember if you were online at the meeting yesterday. I have reported a bug to the astroquery team on their github page. It is something to do with astroquery vizier not returning "object not found" if the query RA and DEC coordinates are outside the search are. They said that vizier has changed something lately (vizier end) so they are fixing the astroquery code at the moment to deal with that. As for timing out, is it pawsey or vizier issue? I am under the impression that it is the vizier issue as I occasionally got timeout issue with the network at home. It seems to me that the server is either up or slow and 1000 is overkilled from others perspective. In any case, the suggestion I got is to use the mirror site. I have added a line (conf.server) in my script to do that, although I will leave the timeout = 1000 there.

**Comment by mattwhiting** [comment]
@biqingfor Generally the timeout of 1000 works well, but I have seen it time out at least once at Pawsey with that - I changed the code I'm running with the pipeline to use 10000, which is why I've put it here.
I'm making another branch that consolidates the changes I've made for the WALLABY script (including similar checks for the get_HIPASS function, and a couple of other things), and will make a similar pull request when I've checked them all in

**Comment by biqingfor** [comment]
@mattwhiting : Thanks. Yes, I haven't wanted to change the timeout knowing it is your way to get around the network, I am still modifying the get_hipass bit to include Northern HIPASS catalogue. The 'no object found' issue came up when I added this new search. It just breaks rather than returning 'no object found'. So your new code to get around this will certainly help.

**Comment by mattwhiting** [comment]
@hyeinyoon Added a couple more fixes to the branch, from getting it running with SB15209

**Comment by hyeinyoon** [comment]
@mattwhiting Many thanks for this change and all others added above, including the timeout option. I found astroquery with the FIRST only returns 50 sources no matter what numbers I use for vizier.row_limit option (i.e. vizier.row_limit = -1 or other numbers). I have checked with the NVSS, but it gives correct different outputs with the different SBIDs well. I guess it is a problem that the CDS team can solve. Also, it would be good if the RACS (and DES for the southern sky) is added together as discussed at the FLASH meeting this morning. I would like try to update this script a little bit more and share it with the team to discuss before I ask you for uploading the script to CASDA this time if you do not mind. I have not merged your pull request yet.

**Pull request merged**
