### PR TITLE
Wallaby operations fixes

### PR DESCRIPTION
**Pull request by mattwhiting**
A pull request for relatively small changes I've made during pilot processing, mostly to overcome issues with rogue bad beams or with fields that didn't return anything in the HIPASS catalogue.
Also a change to avoid picking up the spectral stats plots from continuum cubes (while they aren't processed in standard WALLABY mode, they could be and would otherwise result in the wrong plot being displayed).

### CODE REVIEW

**Comment by mattwhiting** [comment]
Like for the FLASH case, I've added a couple of fixes to get the interactions with files working better

**Comment by biqingfor** [comment]
> A pull request for relatively small changes I've made during pilot processing, mostly to overcome issues with rogue bad beams or with fields that didn't return anything in the HIPASS catalogue. 

OK. 

> Also a change to avoid picking up the spectral stats plots from continuum cubes (while they aren't processed in standard WALLABY mode, they could be and would otherwise result in the wrong plot being displayed).

Will double check.

**Comment by biqingfor** [comment]
-- I noticed the issue with getting ASKAPSoft version. The new version (not yet uploaded) of my script has fixed that using re.findall. It seems like you have caught that issue and fixed it. 

-- Thanks for the get_hipass fixed.

**Review by biqingfor — COMMENTED** [review]
@mattwhiting 
I can't comment under your comment for each change. In any case, I don't think this is correct (change 722a3d4). I downloaded the merged version and tested it independently. The filename now has two ".." rather than "." , which results in files cannot be opened. To note, I am running the script like this "python wallaby_hi_val.py -s 12209 -c 12194" . I didn't specify the imagebase name so the default is used.

**Pull request merged**
